"""unique nombre en modelo de usuario.

Revision ID: c130c7b93721
Revises: edd803e04d4d
Create Date: 2022-10-18 14:01:00.206294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c130c7b93721'
down_revision = 'edd803e04d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usuario', ['nombre'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    # ### end Alembic commands ###
