"""migracion

Revision ID: edd803e04d4d
Revises: 
Create Date: 2022-09-12 10:11:21.517341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edd803e04d4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persona', 'idTipodni',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('persona', 'idLocalidad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('persona', 'idPais',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('persona', 'idSexo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persona', 'idSexo',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('persona', 'idPais',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('persona', 'idLocalidad',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('persona', 'idTipodni',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
